### ISSUE TITLE
Restriction doesn't work on zero section

### ISSUE THREAD

**Issue by Jarvil** [ewallah/moodle-availability_language#10]
Hello,

Language restriction doesn't work on the "zero" section of the course at all, zero section meaning the first section that isn't numbered in Topics format

**Comment by ewallah** [comment]
THX Jarvil for the problem report.

Personally, I never restricted zero sections in my courses, probably because the zero section of a course is a special case (always shown) which had some problems with visibility (https://moodle.org/mod/forum/discuss.php?d=340380 - https://moodle.org/mod/forum/discuss.php?d=357975), but I will investigate what is going on.

- Can you explain what you mean by does not work? Is the section 0 never restricted?
- Can you confirm that other availability restrictions (grade - date) of the zero sections do work?
- Finally can you also mention your Moodle - OS - PHP version?

**Comment by ewallah** [comment]
I do not think this is a bug, but standard Moodle behaviour I see also in other availability restriction plugins. I added some [behat tests](https://github.com/ewallah/moodle-availability_language/commit/9ae569dbe22bb2c8106efa99ddc9539b5658ab29#diff-e048a5189990e75bf8e36a23e4ed2e18) to check the behavior of the zero section and indeed, one cannot tamper with the visibility of the section.

**Comment by ewallah** [comment]
Fixed by removing the possibility to language restrict section 0.

**Comment by Jarvil** [comment]
great, thanks
