### ISSUE TITLE
Add a setting for the default visibility of language restrictions

### ISSUE THREAD

**Issue by izendegi** [ewallah/moodle-availability_language#11]
On this kind of availability restrictions people usually wants the activity/section to be fully hidden for those navigating on other languages because there is usually another activity/section for their language, but by default they're shown greyed-out.

Is it possible to add a feature to set the default visibility (greyed-out/fully hidden) of the activities/sections restricted by language or to set it hidden by default? 

P.S.: I don't really know if this can be done inside the plugin or must be a Moodle core feature...
P.S.2: I've seen there is a closed #3 issue but don't see that functionality implemented.

**Comment by ewallah** [comment]
THX for the report.

Indeed the standard hidden functionality went "missing" during the upgrades, so now I restored this behavior.   I did NOT add a configuration setting because I think this behavior is the most logical one and a default visibility setting should be implemented for all availability plugins.

Let me review and test before the changes arrive in the plugin database.

**Comment by izendegi** [comment]
Thanks for the fast reply!

I agree with you that defaulting this conditions to be hidden is the most reasonable behaviour, so let's leave the setting to be implemented in core for all availability restrictions.

FYI: I've tested your patch on Moodle 3.7.2 and it works as expected.

**Comment by ewallah** [comment]
Fixed
